#include "lcp_catalog.h"

const char lcp_default_repo_data[] =
	"name:nano-nucleos\n"
	"version:1.0.0\n"
	"description:Editor de texto simple para CortexOS\n"
	"arch:x86_64\n"
	"maintainer:CortexOS Team\n"
	"license:MIT\n"
	"dependencies:libc,termcap\n"
	"files:bin/nano-nucleos,share/nano-nucleos/help.txt\n"
	"size:32000\n"
	"repo:cortex.org/main\n"
	"---\n"
	"name:editor-lite\n"
	"version:0.5.0\n"
	"description:Editor de texto ligero para CortexOS\n"
	"arch:x86_64\n"
	"maintainer:CortexOS Team\n"
	"license:MIT\n"
	"dependencies:\n"
	"files:bin/editor-lite\n"
	"size:12500\n"
	"repo:cortex.org/main\n"
	"---\n"
	"name:textpad\n"
	"version:0.9.1\n"
	"description:Editor de texto basado en terminal para CortexOS\n"
	"arch:x86_64\n"
	"maintainer:CortexOS Team\n"
	"license:Apache-2.0\n"
	"dependencies:libc\n"
	"files:bin/textpad\n"
	"size:21200\n"
	"repo:cortex.org/main\n"
	"---\n"
	"name:libc\n"
	"version:1.0.0\n"
	"description:Biblioteca estandar minima para CortexOS\n"
	"arch:x86_64\n"
	"maintainer:CortexOS Team\n"
	"license:MIT\n"
	"dependencies:\n"
	"files:lib/libc.so\n"
	"size:45000\n"
	"repo:cortex.org/main\n"
	"---\n"
	"name:termcap\n"
	"version:1.2.3\n"
	"description:Biblioteca de compatibilidad con terminal para CortexOS\n"
	"arch:x86_64\n"
	"maintainer:CortexOS Team\n"
	"license:BSD-2-Clause\n"
	"dependencies:\n"
	"files:lib/termcap.so\n"
	"size:18000\n"
	"repo:cortex.org/main\n"
	"---\n"
	"name:snake-game\n"
	"version:1.0.0\n"
	"description:Juego clasico de Snake para CortexOS\n"
	"arch:x86_64\n"
	"maintainer:CortexOS Team\n"
	"license:MIT\n"
	"dependencies:\n"
	"files:games/snake-game\n"
	"size:8200\n"
	"repo:cortex.org/games\n"
	"---\n"
	"name:tetris-game\n"
	"version:1.0.0\n"
	"description:Juego clasico de Tetris para CortexOS\n"
	"arch:x86_64\n"
	"maintainer:CortexOS Team\n"
	"license:MIT\n"
	"dependencies:\n"
	"files:games/tetris-game\n"
	"size:11500\n"
	"repo:cortex.org/games\n"
	"---\n"
	"name:pong-game\n"
	"version:1.0.0\n"
	"description:Juego clasico de Pong con CPU para CortexOS\n"
	"arch:x86_64\n"
	"maintainer:CortexOS Team\n"
	"license:MIT\n"
	"dependencies:\n"
	"files:games/pong-game\n"
	"size:7800\n"
	"repo:cortex.org/games\n"
	"---\n"
	"name:2048-game\n"
	"version:1.0.0\n"
	"description:Juego puzzle 2048 para CortexOS\n"
	"arch:x86_64\n"
	"maintainer:CortexOS Team\n"
	"license:MIT\n"
	"dependencies:\n"
	"files:games/2048-game\n"
	"size:9400\n"
	"repo:cortex.org/games\n"
	"---\n"
	"name:ttt-game\n"
	"version:1.0.0\n"
	"description:Tic-Tac-Toe con IA minimax para CortexOS\n"
	"arch:x86_64\n"
	"maintainer:CortexOS Team\n"
	"license:MIT\n"
	"dependencies:\n"
	"files:games/ttt-game\n"
	"size:6200\n"
	"repo:cortex.org/games\n"
	"---\n"
	"name:minesweeper\n"
	"version:1.0.0\n"
	"description:Juego Minesweeper clasico para CortexOS\n"
	"arch:x86_64\n"
	"maintainer:CortexOS Team\n"
	"license:MIT\n"
	"dependencies:\n"
	"files:games/minesweeper\n"
	"size:8900\n"
	"repo:cortex.org/games\n"
	"---\n"
	"name:breakout\n"
	"version:1.0.0\n"
	"description:Juego Breakout con bloques y pelota para CortexOS\n"
	"arch:x86_64\n"
	"maintainer:CortexOS Team\n"
	"license:MIT\n"
	"dependencies:\n"
	"files:games/breakout\n"
	"size:10200\n"
	"repo:cortex.org/games\n"
	"---\n"
	"name:memory-game\n"
	"version:1.0.0\n"
	"description:Juego de memoria con cartas para CortexOS\n"
	"arch:x86_64\n"
	"maintainer:CortexOS Team\n"
	"license:MIT\n"
	"dependencies:\n"
	"files:games/memory-game\n"
	"size:7100\n"
	"repo:cortex.org/games\n"
	"---\n"
	"name:calc-app\n"
	"version:2.0.0\n"
	"description:Calculadora de expresiones para CortexOS\n"
	"arch:x86_64\n"
	"maintainer:CortexOS Team\n"
	"license:MIT\n"
	"dependencies:\n"
	"files:bin/calc-app\n"
	"size:4500\n"
	"repo:cortex.org/tools\n"
	"---\n"
	"name:hexview\n"
	"version:1.0.0\n"
	"description:Visor hexadecimal de archivos para CortexOS\n"
	"arch:x86_64\n"
	"maintainer:CortexOS Team\n"
	"license:MIT\n"
	"dependencies:\n"
	"files:bin/hexview\n"
	"size:3200\n"
	"repo:cortex.org/tools\n"
	"---\n"
	"name:sysinfo\n"
	"version:1.0.0\n"
	"description:Herramienta de informacion del sistema para CortexOS\n"
	"arch:x86_64\n"
	"maintainer:CortexOS Team\n"
	"license:MIT\n"
	"dependencies:\n"
	"files:bin/sysinfo\n"
	"size:5100\n"
	"repo:cortex.org/tools\n"
	"---\n"
	"name:filemanager\n"
	"version:0.8.0\n"
	"description:Gestor de archivos basado en terminal para CortexOS\n"
	"arch:x86_64\n"
	"maintainer:CortexOS Team\n"
	"license:MIT\n"
	"dependencies:libc\n"
	"files:bin/filemanager\n"
	"size:8700\n"
	"repo:cortex.org/tools\n"
	"---\n"
	"name:htop-lite\n"
	"version:0.3.0\n"
	"description:Monitor de procesos y memoria para CortexOS\n"
	"arch:x86_64\n"
	"maintainer:CortexOS Team\n"
	"license:GPL-2.0\n"
	"dependencies:\n"
	"files:bin/htop-lite\n"
	"size:6300\n"
	"repo:cortex.org/tools\n"
	"---\n"
	"name:gpu-driver\n"
	"version:0.1.0\n"
	"description:Driver basico de VGA para CortexOS\n"
	"arch:x86_64\n"
	"maintainer:CortexOS Team\n"
	"license:MIT\n"
	"dependencies:\n"
	"files:drivers/vga-driver.so\n"
	"size:24000\n"
	"repo:cortex.org/drivers\n"
	"---\n"
	"name:net-driver\n"
	"version:0.1.0\n"
	"description:Driver de red RTL8139 para CortexOS\n"
	"arch:x86_64\n"
	"maintainer:CortexOS Team\n"
	"license:MIT\n"
	"dependencies:\n"
	"files:drivers/rtl8139.so\n"
	"size:31000\n"
	"repo:cortex.org/drivers\n"
	"---\n"
	"name:input-driver\n"
	"version:1.0.0\n"
	"description:Driver de entrada PS/2 para CortexOS\n"
	"arch:x86_64\n"
	"maintainer:CortexOS Team\n"
	"license:MIT\n"
	"dependencies:\n"
	"files:drivers/ps2-input.so\n"
	"size:9500\n"
	"repo:cortex.org/drivers\n"
	"---\n"
	"name:libc-dev\n"
	"version:1.0.0\n"
	"description:Archivos de desarrollo de libc para CortexOS\n"
	"arch:x86_64\n"
	"maintainer:CortexOS Team\n"
	"license:MIT\n"
	"dependencies:libc\n"
	"files:include/stdio.h,include/stdlib.h,include/string.h\n"
	"size:12000\n"
	"repo:cortex.org/dev\n"
	"---\n"
	"name:gcc-nucleos\n"
	"version:4.9.0\n"
	"description:Compilador GCC para CortexOS\n"
	"arch:x86_64\n"
	"maintainer:CortexOS Team\n"
	"license:GPL-3.0\n"
	"dependencies:libc\n"
	"files:bin/gcc,libexec/gcc/nucleos/4.9/cc1\n"
	"size:256000\n"
	"repo:cortex.org/dev\n"
	"---\n"
	"name:make-nucleos\n"
	"version:4.2.1\n"
	"description:GNU Make para CortexOS\n"
	"arch:x86_64\n"
	"maintainer:CortexOS Team\n"
	"license:GPL-3.0\n"
	"dependencies:\n"
	"files:bin/make\n"
	"size:42000\n"
	"repo:cortex.org/dev\n"
	"---\n"
	"name:binutils-nucleos\n"
	"version:2.30\n"
	"description:GNU Binutils (as, ld, objdump) para CortexOS\n"
	"arch:x86_64\n"
	"maintainer:CortexOS Team\n"
	"license:GPL-3.0\n"
	"dependencies:\n"
	"files:bin/as,bin/ld,bin/objdump\n"
	"size:89000\n"
	"repo:cortex.org/dev\n"
	"---\n"
	"name:bash-nucleos\n"
	"version:5.1.0\n"
	"description:Bash shell para CortexOS\n"
	"arch:x86_64\n"
	"maintainer:CortexOS Team\n"
	"license:GPL-3.0\n"
	"dependencies:libc,termcap\n"
	"files:bin/bash\n"
	"size:120000\n"
	"repo:extra\n"
	"---\n"
	"name:python-nucleos\n"
	"version:3.9.0\n"
	"description:Python 3 interprete para CortexOS\n"
	"arch:x86_64\n"
	"maintainer:CortexOS Team\n"
	"license:PSF\n"
	"dependencies:libc\n"
	"files:bin/python3,lib/python3.9/\n"
	"size:512000\n"
	"repo:extra\n"
	"---\n"
	"name:wget-nucleos\n"
	"version:1.21.0\n"
	"description:Descargador de archivos HTTP para CortexOS\n"
	"arch:x86_64\n"
	"maintainer:CortexOS Team\n"
	"license:GPL-3.0\n"
	"dependencies:libc\n"
	"files:bin/wget\n"
	"size:28000\n"
	"repo:extra\n"
	"---\n"
	"name:curl-nucleos\n"
	"version:7.80.0\n"
	"description:Cliente URL multiprotocolo para CortexOS\n"
	"arch:x86_64\n"
	"maintainer:CortexOS Team\n"
	"license:MIT\n"
	"dependencies:libc\n"
	"files:bin/curl\n"
	"size:35000\n"
	"repo:extra\n";
